name: Java

on: # trigger the automated ci/cd
    push:
        branches:
            - "master"

#defaults:
#  run:
#    working-directory: ./app

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # build machine
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build and push docker image
              run: |
                docker login ghcr.io -u ${{ secrets.GH_USERNAME }} -p ${{ secrets.GH_PAT }}
                docker build -t ghcr.io/${{ secrets.GH_USERNAME }}/test-github-action:latest .
    
                docker push ghcr.io/${{ secrets.GH_USERNAME }}/test-github-action:latest
            - name: Restart K3S deployment
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                # rollout your deployment
                script: |
                  kubectl create secret docker-registry secret --docker-server=https://ghcr.io --docker-username=${{ secrets.GH_USERNAME }} --docker-password=${{ secrets.GH_PAT }}
                  cd ~/helm-charts/test-github-action/k8s
                  helm upgrade --install test-github-action -f test-github-action/values.yaml ./test-github-action